# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b2d669716390634c42afa6f158ca5e7df370b4c84b8153278ddf9c903b626dbccfca0e1c8c1f5f62d4842d2349a7aa4178fac49b1494e29d8d1dbbbf54c50da0

test:
  secret_key_base: 1306e9b71a81b8f9d9a9b62137a63632cb5fcc9c72cb20c821c69ec6823b87d02e0fa06bca90b40c89cfedcfa2546442e0796dfba4c66a3258706b8d0b675ff8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
